### PR TITLE
Bug: Request IDs are duplicated in firefox

### LINKED ISSUE #92: Request id's are duplicated in firefox
I just discovered that safe apps that use RPC calls aren't working well in firefox because for some reason request ids are duplicated, and it's all because:
`window?.performance.now().toString(36); // this is the code used to generate a request id`
In chrome, it would return something like 251131.48499999807 but in Firefox it returns only the integer part, turns out they did it to protect from fingerprinting :exploding_head:

### PR DESCRIPTION
**Pull request by mikheevm**
This PR:
- Fixes #92 by using `window.crypto` for generating request id
- Remove bash script for travis which is not needed anymore

### CODE REVIEW

File: packages/safe-apps-sdk/jest/setup.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    e.message =
+      "Failed to execute 'getRandomValues' on 'Crypto': The " +
+      "ArrayBufferView's byte length (" +
+      buf.length +
+      ') exceeds the ' +
+      'number of bytes of entropy available via this API (65536).';
+    e.name = 'QuotaExceededError';
+    throw e;
+  }
+  const bytes = crypto.randomBytes(buf.length);
```
Comment (rmeissner) [inline packages/safe-apps-sdk/jest/setup.ts:18]: Why not use Math.random?

Comment (rmeissner) [reply packages/safe-apps-sdk/jest/setup.ts:18]: if it is because Math.random is not random enought you can just hash `new Date().getTime()` with it.

So something like `sha256((new Date()).getTime().toString() + randomString)`

random string could be based on https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript

In general I don't mind ... but I had issue with crypto before during development because it was not available in "unsecure" environments. (https://dev.to/hoffmann/cannot-read-property-digest-of-undefined-51np)

File: packages/safe-apps-sdk/src/communication/utils.ts [hunk 2]
```diff
@@ -1,6 +1,15 @@
+// i.e. 0-255 -> '00'-'ff'
+const dec2hex = (dec: number): string => dec.toString(16).padStart(2, '0');
+
+const generateId = (len: number): string => {
+  const arr = new Uint8Array((len || 40) / 2);
+  window.crypto.getRandomValues(arr);
```
Comment (rmeissner) [inline packages/safe-apps-sdk/src/communication/utils.ts:6]: Maybe handle the case that `window.crypto` is not defined (see comment above)

**Review by rmeissner — APPROVED** [review]

File: packages/safe-apps-sdk/jest/setup.ts (hunk 1 above)
Comment (rmeissner) [reply packages/safe-apps-sdk/jest/setup.ts:18]: Ohhh actually the `getRandomValues` is the only method always available ... so we can ignore that.

https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto
```
Although window.crypto is available on all windows, the returned Crypto object only has one usable feature in insecure contexts: the getRandomValues() method. In general, you should use this API only in secure contexts.
```

Comment (mikheevm) [reply packages/safe-apps-sdk/jest/setup.ts:18]: > So something like sha256((new Date()).getTime().toString() + randomString)
>
> random string could be based on https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript

It's more complex than the approach I took, isn't it? So currently there's only `randomString` part which is generated via `getRandomValues`
